# Site settings
title: sandyjmacdonald
email: sandyjmacdonald@gmail.com
author: Sandy Macdonald
tagline: 'A veritable smorgasbord of content'
description: 'A veritable smorgasbord of content'
baseurl: ''
url: 'http://sandyjmacdonald.github.io'

# Google analytics
google_analytics: UA-58080101-1

# Optional features
animated: false
show_related_posts: true
show_post_footers: false
show_social_icons: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: sandyjmacdonald
stackoverflow_id:
twitter_username: sandyjmacdonald
facebook_username: sandyjmacdonald
google_plus_id:
linkedin_username:
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: false
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: false

# Build settings
markdown: kramdown
highlighter: rouge
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'footnotes']
permalink: pretty
paginate: 6
sass:
  compressed: true
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gensocial
